version: "3.7"

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./code-chat/data/instances:/var/www/instances
      - ./code-chat/:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
      - ./.docker/nginx/log/:/var/log/nginx/
    depends_on:
      - n8n
    networks:
      - chat-boot

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=root
      - N8N_BASIC_AUTH_PASSWORD=root
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_DATABASE=chat_boot
      - DB_MYSQLDB_HOST=mysql
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_USER=root
      - DB_MYSQLDB_PASSWORD=root
    volumes:
      - ./.docker/.n8n:/home/node/.n8n
    depends_on:
      - mysql
    networks:
      - chat-boot
  # db mysql
  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: chat_boot
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - ./.docker/.mysql/dbdata:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - chat-boot
  chat:
    image: allanmilani/code-chat:1.0.0
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./code-chat/data/instances:/var/www/instances
      - ./code-chat/env.yml:/var/www/src/env.yml
      - ./code-chat/src/main.ts:/var/www/src/main.ts
      - ./code-chat/views/qrcode.hbs:/var/www/views/qrcode.hbs
    depends_on:
      - redis
      - mongodb
    networks:
      - chat-boot

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./code-chat/data/mongodb:/data/db
    ports:
      - 26712:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: DhxTJAA0RPoVTR6
    networks:
      - chat-boot
    expose:
      - 26712
    # redis
  redis:
    image: redis:latest
    networks:
      - chat-boot

networks:
  chat-boot:
    driver: bridge
